namespace :db do
  desc "Sets up the database with look ups and some sample organisation, function, user data."
  task :bootstrap => :environment do
    
    puts "Please enter the e-mail address you wish to use for the administrator:"
    email = STDIN.gets.chomp!
    admin = Administrator.create(:email => email)
    admin.passkey = User.generate_passkey(admin)
    admin.save
    puts "Administrator created. Their passkey is #{admin.passkey}."
    puts "Log-in with: http://server/#{admin.passkey}"

    #     Administrator.create(:email => 'Iain_Wilkinson@blackradley.com')
    #     Administrator.create(:email => 'Peter_Latchford@blackradley.com')
    #     Administrator.create(:email => 'drbollins@hotmail.com')
    # 
    #     # Create birmingham as an organisation attached to Birmingham user
    #     organisational_manager = OrganisationManager.create(:email => 'Peter_Latchford@blackradley.com')
    #     Organisation.create(:user_id => organisational_manager.id,
    #     :name => 'Birmingham City Council',
    #     :style => 'birmingham',
    #     :strategies_help => 'Help for Birmingham strategies required',
    #     :impact_groups_help => 'Help for Birmingham impact groups required',
    #     :good_equality_groups_help => 'Help for Birmingham good equality groups required',
    #     :bad_equality_groups_help => 'Help for Birmingham bad equality groups required',
    #     :approval_help => 'Help for Birmingham approval required')
    # 
    #     # Five functions for birmingham
    #     birmingham = Organisation.find(:first, :conditions => "style = 'birmingham'")
    #     # Community Strategy
    #     user = FunctionManager.create(:email => 'Peter_Latchford@blackradley.com')
    #     Function.create(:user_id => user.id,
    #       :organisation_id => birmingham.id,
    #       :name => 'Community Strategy',
    #       :existence_status => 1,
    #       :impact_service_users => 3,
    #       :impact_staff => 1,
    #       :impact_supplier_staff => 2,
    #       :impact_partner_staff => 3,
    #       :impact_employees => 4,
    #       :good_gender => 1,
    #       :good_race => 1,
    #       :good_disability => 3,
    #       :good_faith => 1,
    #       :good_sexual_orientation => 1,
    #       :good_age => 1,
    #       :bad_gender => 1,
    #       :bad_race => 1,
    #       :bad_disability => 1,
    #       :bad_faith => 2,
    #       :bad_sexual_orientation => 1,
    #       :bad_age => 1,
    #       :approved => 1,
    #       :approver => 'Iain Wilkinson') 
    #     user = FunctionManager.create(:email => 'Iain_Wilkinson@blackradley.com')
    #     # Publications
    #     Function.create(:user_id => user.id,
    #       :organisation_id => birmingham.id,
    #       :name => 'Publications',
    #       :existence_status => 1,
    #       :impact_service_users => 3,
    #       :impact_staff => 1,
    #       :impact_supplier_staff => 2,
    #       :impact_partner_staff => 3,
    #       :impact_employees => 4,
    #       :good_gender => 1,
    #       :good_race => 1,
    #       :good_disability => 3,
    #       :good_faith => 1,
    #       :good_sexual_orientation => 1,
    #       :good_age => 1,
    #       :bad_gender => 1,
    #       :bad_race => 1,
    #       :bad_disability => 1,
    #       :bad_faith => 2,
    #       :bad_sexual_orientation => 1,
    #       :bad_age => 1,
    #       :approved => 0,
    #       :approver => 'Peter Latchford')   
    #     # Meals on Wheels
    #     user = FunctionManager.create(:email => 'Joe_Collins@blackradley.com')
    #     Function.create(:user_id => user.id,
    #       :organisation_id => birmingham.id,
    #       :name => 'Meals on Wheels',
    #       :existence_status => 2,
    #       :impact_service_users => 0,
    #       :impact_staff => 3,
    #       :impact_supplier_staff => 2,
    #       :impact_partner_staff => 0,
    #       :impact_employees => 0,
    #       :good_gender => 0,
    #       :good_race => 1,
    #       :good_disability => 0,
    #       :good_faith => 0,
    #       :good_sexual_orientation => 0,
    #       :good_age => 0,
    #       :bad_gender => 1,
    #       :bad_race => 0,
    #       :bad_disability => 0,
    #       :bad_faith => 1,
    #       :bad_sexual_orientation => 0,
    #       :bad_age => 0,
    #       :approved => 0,
    #       :approver => 'Iain Wilkinson')
    #     user = FunctionManager.create(:email => 'drbollins@hotmail.com')
    #     Function.create(:user_id => user.id,
    #       :organisation_id => birmingham.id,
    #       :name => 'Drugs and Alcohol',
    #       :existence_status => 1,
    #       :impact_service_users => 0,
    #       :impact_staff => 0,
    #       :impact_supplier_staff => 0,
    #       :impact_partner_staff => 0,
    #       :impact_employees => 0,
    #       :good_gender => 0,
    #       :good_race => 0,
    #       :good_disability => 0,
    #       :good_faith => 0,
    #       :good_sexual_orientation => 0,
    #       :good_age => 0,
    #       :bad_gender => 0,
    #       :bad_race => 0,
    #       :bad_disability => 0,
    #       :bad_faith => 0,
    #       :bad_sexual_orientation => 0,
    #       :bad_age => 0,
    #       :approved => 0,
    #       :approver => '')
    #     user = FunctionManager.create(:email => 'Peter_Latchford@blackradley.com')
    #     Function.create(:user_id => user.id,
    #       :organisation_id => birmingham.id,
    #       :name => 'Occupational Therapy',
    #       :existence_status => 2,
    #       :impact_service_users => 3,
    #       :impact_staff => 1,
    #       :impact_supplier_staff => 2,
    #       :impact_partner_staff => 3,
    #       :impact_employees => 4,
    #       :good_gender => 1,
    #       :good_race => 1,
    #       :good_disability => 3,
    #       :good_faith => 1,
    #       :good_sexual_orientation => 1,
    #       :good_age => 1,
    #       :bad_gender => 1,
    #       :bad_race => 1,
    #       :bad_disability => 1,
    #       :bad_faith => 3,
    #       :bad_sexual_orientation => 1,
    #       :bad_age => 1,
    #       :approved => 1,
    #       :approver => 'Iain Wilkinson')
    # 
    #     $NO_ANSWER = 'Not answered yet'
    #     # Existing/Proposed
    #     LookUp.create(:look_up_type => LookUp::TYPE[:existing_proposed],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 15,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:existing_proposed],
    #     :name => 'Proposed',
    #     :value => 1,
    #     :weight => 15,
    #     :description => 'Proposed',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:existing_proposed],
    #     :name => 'Existing',
    #     :value => 2,
    #     :weight => 5,
    #     :description => 'Existing',
    #     :position => 2)
    # 
    #     # Yes/No
    #     LookUp.create(:look_up_type => LookUp::TYPE[:yes_no],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 5,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:yes_no],
    #     :name => 'Yes',
    #     :value => 1,
    #     :weight => 5,
    #     :description => 'Yes',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:yes_no],
    #     :name => 'No',
    #     :value => 2,
    #     :weight => 5,
    #     :description => 'No',
    #     :position => 2)
    # 
    #     # Amount of impact
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_amount],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 0,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_amount],
    #     :name => 'None',
    #     :value => 1,
    #     :weight => 1,
    #     :description => 'None',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_amount],
    #     :name => 'Small minority',
    #     :value => 2,
    #     :weight => 5,
    #     :description => 'Small minority',
    #     :position => 2)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_amount],
    #     :name => 'Significant minority',
    #     :value => 3,
    #     :weight => 5,
    #     :description => 'Significant minority',
    #     :position => 3)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_amount],
    #     :name => 'About half',
    #     :value => 4,
    #     :weight => 5,
    #     :description => 'About half',
    #     :position => 4)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_amount],
    #     :name => 'Majority',
    #     :value => 5,
    #     :weight => 5,
    #     :description => 'Majority',
    #     :position => 5)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_amount],
    #     :name => 'Substantial majority',
    #     :value => 6,
    #     :weight => 5,
    #     :description => 'Substantial majority',
    #     :position => 6)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_amount],
    #     :name => 'All',
    #     :value => 7,
    #     :weight => 5,
    #     :description => 'All',
    #     :position => 7)
    # 
    #     # Level of impact
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_level],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 15,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_level],
    #     :name => 'None',
    #     :value => 1,
    #     :weight => 5,
    #     :description => 'None at all',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_level],
    #     :name => 'Limited',
    #     :value => 2,
    #     :weight => 10,
    #     :description => 'Some impact',
    #     :position => 2)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:impact_level],
    #     :name => 'Significant',
    #     :value => 3,
    #     :weight => 15,
    #     :description => 'Significant impact',
    #     :position => 3)
    # 
    #     # Rating
    #     LookUp.create(:look_up_type => LookUp::TYPE[:rating],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 0,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:rating],
    #     :name => '5 - excellent',
    #     :value => 5,
    #     :weight => 10,
    #     :description => '5 - excellent',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:rating],
    #     :name => '4 - good',
    #     :value => 4,
    #     :weight => 15,
    #     :description => '4 - good',
    #     :position => 2)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:rating],
    #     :name => '3 - at expectations',
    #     :value => 3,
    #     :weight => 20,
    #     :description => '3 - at expectations',
    #     :position => 3)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:rating],
    #     :name => '2 - below expectations',
    #     :value => 2,
    #     :weight => 25,
    #     :description => '2 - below expectations',
    #     :position => 4)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:rating],
    #     :name => '1 - poor',
    #     :value => 1,
    #     :weight => 30,
    #     :description => '1 - poor',
    #     :position => 5)
    # 
    #     # Yes/No/Not sure
    #     LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 0,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure],
    #     :name => 'Yes',
    #     :value => 1,
    #     :weight => 0,
    #     :description => 'Yes',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure],
    #     :name => 'No',
    #     :value => 2,
    #     :weight => 0,
    #     :description => 'No',
    #     :position => 2)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure],
    #     :name => 'Not sure',
    #     :value => 3,
    #     :weight => 0,
    #     :description => 'Not sure',
    #     :position => 3)     
    # 
    #     # Rating
    #     LookUp.create(:look_up_type => LookUp::TYPE[:timescales],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 0,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:timescales],
    #     :name => 'Less than six months',
    #     :value => 1,
    #     :weight => 0,
    #     :description => 'Less than six months',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:timescales],
    #     :name => 'Six months to a year',
    #     :value => 2,
    #     :weight => 0,
    #     :description => 'Six months to a year',
    #     :position => 2)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:timescales],
    #     :name => 'Over a year',
    #     :value => 3,
    #     :weight => 0,
    #     :description => 'Over a year',
    #     :position => 3)
    #     
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_groups],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 0,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_groups],
    #     :name => 'No relevant groups',
    #     :value => 1,
    #     :weight => 3,
    #     :description => 'No relevant groups',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_groups],
    #     :name => 'Plans to consult',
    #     :value => 2,
    #     :weight => 0,
    #     :description => 'Plans to consult',
    #     :position => 2)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_groups],
    #     :name => 'No plans to consult',
    #     :value => 3,
    #     :weight => 0,
    #     :description => 'No plans to consult',
    #     :position => 3)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_groups],
    #     :name => 'Not sure',
    #     :value => 4,
    #     :weight => 0,
    #     :description => 'Not sure',
    #     :position => 4) 
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_groups],
    #     :name => 'Not applicable',
    #     :value => 5,
    #     :weight => 0,
    #     :description => 'Not applicable',
    #     :position => 5)        
    # 
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_experts],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 0,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_experts],
    #     :name => 'No relevant experts',
    #     :value => 1,
    #     :weight => -2,
    #     :description => 'No relevant experts',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_experts],
    #     :name => 'Plans to consult',
    #     :value => 2,
    #     :weight => 0,
    #     :description => 'Plans to consult',
    #     :position => 2)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_experts],
    #     :name => 'No plans to consult',
    #     :value => 3,
    #     :weight => 0,
    #     :description => 'No plans to consult',
    #     :position => 3)    
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_experts],
    #     :name => 'Not sure',
    #     :value => 4,
    #     :weight => 0,
    #     :description => 'Not sure',
    #     :position => 4)    
    #     LookUp.create(:look_up_type => LookUp::TYPE[:consult_experts],
    #     :name => 'Not applicable',
    #     :value => 5,
    #     :weight => 0,
    #     :description => 'Not applicable',
    #     :position => 5)    
    #     
    #     # Function/Policy
    #     LookUp.create(:look_up_type => LookUp::TYPE[:function_policy],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 0,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:function_policy],
    #     :name => 'Function',
    #     :value => 1,
    #     :weight => 0,
    #     :description => 'Function',
    #     :position => 1)
    #     LookUp.create(:look_up_type => LookUp::TYPE[:function_policy],
    #     :name => 'Policy',
    #     :value => 2,
    #     :weight => 0,
    #     :description => 'Policy',
    #     :position => 2)
    #     
    #       #yes/no/notsure = 10/0/10
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_10_0],
    #     :name => $NO_ANSWER,
    #     :value => 0,
    #     :weight => 0,
    #     :description => $NO_ANSWER,
    #     :position => 0)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_10_0],
    # :name => 'Yes',
    # :value => 1,
    # :weight => 10,
    # :description => 'Yes',
    # :position => 1)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_10_0],
    # :name => 'No',
    # :value => 2,
    # :weight => 0,
    # :description => 'No',
    # :position => 2)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_10_0],
    # :name => 'Not sure',
    # :value => 3,
    # :weight => 10,
    # :description => 'Not sure',
    # :position => 3) 
    # 
    #       #Yes/no/notsure = -5/0/0
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_n5_0],
    # :name => $NO_ANSWER,
    # :value => 0,
    # :weight => 0,
    # :description => $NO_ANSWER,
    # :position => 0)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_n5_0],
    # :name => 'Yes',
    # :value => 1,
    # :weight => -5,
    # :description => 'Yes',
    # :position => 1)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_n5_0],
    # :name => 'No',
    # :value => 2,
    # :weight => 0,
    # :description => 'No',
    # :position => 2)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_n5_0],
    # :name => 'Not sure',
    # :value => 3,
    # :weight => 0,
    # :description => 'Not sure',
    # :position => 3) 
    # 
    #       #yes/no/notsure = -3/0/0
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_n3_0],
    # :name => $NO_ANSWER,
    # :value => 0,
    # :weight => 0,
    # :description => $NO_ANSWER,
    # :position => 0)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_n3_0],
    # :name => 'Yes',
    # :value => 1,
    # :weight => -3,
    # :description => 'Yes',
    # :position => 1)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_n3_0],
    # :name => 'No',
    # :value => 2,
    # :weight => 0,
    # :description => 'No',
    # :position => 2)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_n3_0],
    # :name => 'Not sure',
    # :value => 3,
    # :weight => 0,
    # :description => 'Not sure',
    # :position => 3)
    # 
    #       #yes/no/notsure = 3/10/10
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_3_10],
    # :name => $NO_ANSWER,
    # :value => 0,
    # :weight => 0,
    # :description => $NO_ANSWER,
    # :position => 0)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_3_10],
    # :name => 'Yes',
    # :value => 1,
    # :weight => 3,
    # :description => 'Yes',
    # :position => 1)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_3_10],
    # :name => 'No',
    # :value => 2,
    # :weight => 10,
    # :description => 'No',
    # :position => 2)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_3_10],
    # :name => 'Not sure',
    # :value => 3,
    # :weight => 10,
    # :description => 'Not sure',
    # :position => 3) 
    # 
    #       #yes/no/notsure = 2/5/5
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_2_5],
    # :name => $NO_ANSWER,
    # :value => 0,
    # :weight => 0,
    # :description => $NO_ANSWER,
    # :position => 0)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_2_5],
    # :name => 'Yes',
    # :value => 1,
    # :weight => 2,
    # :description => 'Yes',
    # :position => 1)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_2_5],
    # :name => 'No',
    # :value => 2,
    # :weight => 5,
    # :description => 'No',
    # :position => 2)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_2_5],
    # :name => 'Not sure',
    # :value => 3,
    # :weight => 5,
    # :description => 'Not sure',
    # :position => 3)
    # 
    #       #yes/no/notsure = 15/0/15
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_15_0],
    # :name => $NO_ANSWER,
    # :value => 0,
    # :weight => 0,
    # :description => $NO_ANSWER,
    # :position => 0)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_15_0],
    # :name => 'Yes',
    # :value => 1,
    # :weight => 15,
    # :description => 'Yes',
    # :position => 1)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_15_0],
    # :name => 'No',
    # :value => 2,
    # :weight => 0,
    # :description => 'No',
    # :position => 2)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_15_0],
    # :name => 'Not sure',
    # :value => 3,
    # :weight => 15,
    # :description => 'Not sure',
    # :position => 3)
    # 
    #       #yes/no/notsure = 3/0/3
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_3_0],
    # :name => $NO_ANSWER,
    # :value => 0,
    # :weight => 0,
    # :description => $NO_ANSWER,
    # :position => 0)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_3_0],
    # :name => 'Yes',
    # :value => 1,
    # :weight => 3,
    # :description => 'Yes',
    # :position => 1)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_3_0],
    # :name => 'No',
    # :value => 2,
    # :weight => 0,
    # :description => 'No',
    # :position => 2)
    #       LookUp.create(:look_up_type => LookUp::TYPE[:yes_no_notsure_3_0],
    # :name => 'Not sure',
    # :value => 3,
    # :weight => 3,
    # :description => 'Not sure',
    # :position => 3)    
    # 
    #     birmingham = Organisation.find(:first, :conditions => "style = 'birmingham'")
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'Manage resources effectively, flexibly and responsively',
    #       :description => 'Manage resources effectively, flexibly and responsively',
    #       :position => 0)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'Investing in our staff to build an organisation that is fit for its purpose',
    #       :description => 'Investing in our staff to build an organisation that is fit for its purpose',
    #       :position => 1)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'Raising performance in our services for children, young people, families and adult',
    #       :description => 'Raising performance in our services for children, young people, families and adult',
    #       :position => 2)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'Raising performance in our housing services',
    #       :description => 'Raising performance in our housing services',
    #       :position => 3)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'Cleaner, greener and safer city – Your City, Your Birmingham',
    #       :description => 'Cleaner, greener and safer city – Your City, Your Birmingham',
    #       :position => 4)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'Investing in regeneration',
    #       :description => 'Investing in regeneration',
    #       :position => 5)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => "Improving the city's transport and tackling congestion",
    #       :description => "Improving the city's transport and tackling congestion",
    #       :position => 6)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'A fair and welcoming city',
    #       :description => 'A fair and welcoming city',
    #       :position => 7)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'Providing more effective education and leisure opportunities',
    #       :description => 'Providing more effective education and leisure opportunities',
    #       :position => 8)
    #     Strategy.create(:organisation_id => birmingham.id,
    #       :name => 'Promoting Birmingham as a great international city',
    #       :description => 'Promoting Birmingham as a great international city',
    #       :position => 9)
    # 
    #     # Strategy responses for Birmingham
    #     birmingham = Organisation.find(:first, :conditions => "style = 'birmingham'")
    #     # Birminham's first function
    #     first_function = birmingham.functions.first
    #     birmingham.strategies.each do |function_strategy|
    #       function_response = first_function.function_strategies.find_or_create_by_strategy_id(function_strategy.id)
    #       function_response.strategy_response = (rand + 1).round
    #       function_response.save
    #     end    
    #     # Birminham's last function
    #     last_function = birmingham.functions.last
    #     birmingham.strategies.each do |function_strategy|
    #       function_response = last_function.function_strategies.find_or_create_by_strategy_id(function_strategy.id)
    #       function_response.strategy_response = (rand + 1).round
    #       function_response.save
    #     end
    
  end
end