# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'http://rubygems.org'

gem 'rails', "~> 4.0"
gem 'haml'
gem "mysql2"
gem "jquery-rails"
# gem 'jquery-colorbox-rails'

#gem 'rmagick', :require => 'RMagick'
gem 'pdf-writer', git: "https://github.com/Hermanverschooten/pdf-writer.git"
gem 'newrelic_rpm'
# gem "devise", "= 1.5.2"
gem 'formtastic', "~> 2"
gem 'airbrake'
gem 'rails3-jquery-autocomplete'
gem 'devise_security_extension'
gem 'right_aws'
gem 'rack-ssl', :require => 'rack/ssl'
gem 'whenever'
gem 'will_paginate', "~> 3.0.pre2"

gem 'rake'
gem 'acts_as_list'
gem "protected_attributes"

gem 'sprockets'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'

gem 'activerecord-session_store'
gem 'responders', '~> 2.0'

group :test do
  gem 'test-unit'
  gem 'factory_girl', "1.3.3"
  gem 'shoulda'
  gem 'mocha'
  gem "test_after_commit"
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  # gem "rcov_rails"
  gem 'mail_safe'

  gem 'capistrano', '~> 3.0', require: false
  gem 'capistrano-rails',   '~> 1.1', require: false
  gem 'capistrano-bundler', '~> 1.1', require: false
  gem 'capistrano-rvm',   '~> 0.1', require: false

  gem 'db_fixtures_dump'
end
