# The order matters!
---
javascripts:
- base:
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - commentsandnotes
  - prototip
stylesheets:
# error.css is never called through Rails so not included here
- base:
  - help_text
  - prototip
  - general
  - links
  - buttons
  - layout
  - mainMenu
  - sectionsMenu
  - strandMenu
  - tables
  - stepPage
  - strategy
  - activity
  - errors
  - formatting
  - questions
  - organisation
  - summaryPage
# create per-customer packages for customising in the future and conditional includes
- alisonmclean:
  - organisations/alisonmclean
- baddiley:
  - organisations/baddiley
- birmingham:
  - organisations/birmingham
- bradford:
  - organisations/bradford
- brap:
  - organisations/brap
- brettonwood:
  - organisations/brettonwood
- caret:
  - organisations/caret
- cskstrategies:
  - organisations/cskstrategies
- ealing:
  - organisations/ealing
- hertfordshire:
  - organisations/hertfordshire
- lambeth:
  - organisations/lambeth
- stratford:
  - organisations/stratford
- thechangeagency:
  - organisations/thechangeagency
- wolverhampton:
  - organisations/wolverhampton