# The order matters!
--- 
javascripts: 
- base: 
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - commentsandnotes
  - tooltip
stylesheets:
# error.css is never called through Rails so not included here
- base: 
  - default
  - tooltip
# create per-customer packages for customising in the future and conditional includes
- alisonmclean:
  - organisations/alisonmclean
- baddiley:
  - organisations/baddiley
- birmingham:
  - organisations/birmingham
- bradford:
  - organisations/bradford
- brap:
  - organisations/brap
- brettonwood:
  - organisations/brettonwood
- caret:
  - organisations/caret
- cskstrategies:
  - organisations/cskstrategies
- ealing:
  - organisations/ealing
- hertfordshire:
  - organisations/hertfordshire
- stratford:
  - organisations/stratford
- thechangeagency:
  - organisations/thechangeagency
- wolverhampton:
  - organisations/wolverhampton