# The order matters!
---
javascripts:
- base:
  - jquery
  # - prototype
  - jquery_fancybox-1_3_0
  # - effects
  # - dragdrop
  # - controls
  - application
  - rails
  - jquery-ui.min
  # - commentsandnotes
  # - prototip
stylesheets:
# error.css is never called through Rails so not included here
- base:
  - jquery_fancybox-1_3_0
  - fancybox_extensions
  - help_text
  - prototip
  - directorate
  - general
  - links
  - buttons
  - layout
  - mainMenu
  - sectionsMenu
  - strandMenu
  - tables
  - stepPage
  - strategy
  - activity
  - project
  - errors
  - formatting
  - questions
  - organisation
  - summaryPage
