development:
  address: smtp.blackradley.com #62.193.206.5
  server: pop.blackradley.com
  port: 25
  domain: blackradley.com    
  authentication: plain
  username: iain_wilkinson@blackradley.com
  password: gubbing
staging:
  address: smtp.blackradley.com  #62.193.206.5
  port: 25
  domain: blackradley.com
  authentication: plain
  username: iain_wilkinson@blackradley.com
  password: gubbing  
production:
  address: smtp.blackradley.com #62.193.206.5
  server: pop.blackradley.com
  port: 25
  domain: blackradley.com    
  authentication: plain
  username: support@blackradley.com
  password: support
  authentication: plain
demonstration:
  server: localhost
  port: 25
  domain: localhost
  #authentication: login
  username: none
  password: none