development:
  server: webmail5.amenworld.com #mail.protectedservice.net
  port: 25
  domain: www.blackradley.com
  authentication: login
  username: Iain_Wilkinson@blackradley.com
  password: gubbing
staging:
  server: webmail5.amenworld.com#mail.protectedservice.net
  port: 25
  domain: www.blackradley.com
  authentication: login
  username: Iain_Wilkinson@blackradley.com
  password: gubbing  
production:
  server: webmail5.amenworld.com #mail.protectedservice.net
  port: 25
  domain: www.blackradley.com
  authentication: login
  username: Iain_Wilkinson@blackradley.com
  password: gubbing
demonstration:
  server: localhost
  port: 25
  domain: localhost
  authentication: login
  username: none
  password: none