development:
  server: zimbra.protectedservice.net #mail.protectedservice.net
  port: 25
  domain: www.blackradley.com
  authentication: login
  username: Iain_Wilkinson@blackradley.com
  password: callustu
staging:
  server: zimbra.protectedservice.net #mail.protectedservice.net
  port: 25
  domain: www.blackradley.com
  authentication: login
  username: Iain_Wilkinson@blackradley.com
  password: callustu  
production:
  server: zimbra.protectedservice.net#mail.protectedservice.net
  port: 25
  domain: www.blackradley.com
  authentication: login
  username: Iain_Wilkinson@blackradley.com
  password: callustu
demonstration:
  server: localhost
  port: 25
  domain: localhost
  authentication: login
  username: none
  password: none