development:
  server: mail.protectedservice.net
  port: 25
  domain: www.blackradley.com
  authentication: login
  username: Iain_Wilkinson@blackradley.com
  password: callustu
staging:
  server: localhost
  port: 25
  domain: impactstaging.org.uk
  authentication: login
  username: buxton
  password: MineralWater
production:
  server: mail.protectedservice.net
  port: 25
  domain: www.blackradley.com
  authentication: login
  username: Iain_Wilkinson@blackradley.com
  password: callustu