development:
  address: 62.193.206.5#mail.protectedservice.net
  port: 25
  domain: blackradley.com
  authentication: login
  username: iain_wilkinson
  password: gubbing
staging:
  address: 62.193.206.5#mail.protectedservice.net
  port: 25
  domain: blackradley.com
  authentication: login
  username: iain_wilkinson
  password: gubbing  
production:
  address: 62.193.206.5#mail.protectedservice.net
  port: 25
  domain: blackradley.com
  authentication: login
  username: iain_wilkinson
  password: gubbing
demonstration:
  server: localhost
  port: 25
  domain: localhost
  #authentication: login
  username: none
  password: none