#!/usr/bin/env bash
case $1 in
	"staging" )
	ssh buxton@buxton.test.27stars.co.uk
	;;
	"production" )
	ssh serveradmin@impactengine.org.uk@ftp.s21552.gridserver.com
	;;
	"production2" )
	ssh buxton@webwelcome.net
	;;
esac