#!/usr/bin/env bash
case $1 in
	"staging" )
	ssh buxton@impactstaging.org.uk -p 1417
	;;
	"staging_old" )
	ssh buxton@buxton.test.27stars.co.uk
	;;
	"production" )
	ssh buxton@impactengine.org.uk -p 1417
	;;
	"production_old" )
	ssh serveradmin@webwelcome.net@ftp.s21552.gridserver.com
	;;
esac